
###
GET http://localhost:3333/carros


###

POST http://localhost:3333/carros
Content-Type: application/json

{
    "marca": "Wolkswagem",
    "modelo": "Golf GTI",
    "placa": "RYU2112"
}

###

PUT http://localhost:3333/carros/48720f0e-f6e0-42e0-b326-8d65ee97fb36
Content-Type: application/json

{
    "marca": "Mercedes-Benz",
    "modelo": "AMG GTR",
    "placa": "LUNA2112"
}

###

DELETE http://localhost:3333/carros/id
